# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetNumberAndName', models.CharField(blank=True, max_length=200)),
                ('apartmentNo', models.CharField(blank=True, max_length=4)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zipCode', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ContactSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyCompleted', models.BooleanField()),
                ('homePhoneNumber', models.CharField(blank=True, max_length=11)),
                ('mailingAddress', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail', to='enroller.Address')),
                ('physicalAddress', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical', to='enroller.Address')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAndHealthInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyCompleted', models.BooleanField()),
                ('confidentialInfoBox1', models.CharField(blank=True, max_length=100)),
                ('confidentialInfoBox2', models.NullBooleanField()),
                ('doctorName', models.CharField(blank=True, max_length=100)),
                ('doctorPhoneNumber', models.CharField(blank=True, max_length=11)),
                ('studentHealthInsurace', models.CharField(blank=True, max_length=100)),
                ('illinoisMedicalCardID', models.CharField(blank=True, max_length=9)),
                ('guardianArmedForces', models.NullBooleanField()),
                ('guardianExpectingDeployment', models.NullBooleanField()),
                ('informationCertification', models.NullBooleanField()),
                ('dateFormFilledOut', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('relationship', models.CharField(blank=True, max_length=20)),
                ('livesWith', models.NullBooleanField()),
                ('getsMailings', models.NullBooleanField()),
                ('emergency', models.NullBooleanField()),
                ('permissionToPickup', models.NullBooleanField()),
                ('homePhoneNumber', models.CharField(blank=True, max_length=11)),
                ('cellPhoneNumber', models.CharField(blank=True, max_length=11)),
                ('emailAddress', models.CharField(blank=True, max_length=200)),
                ('nameOfEmployer', models.CharField(blank=True, max_length=100)),
                ('workPhoneNumber', models.CharField(blank=True, max_length=11)),
                ('communicationLanguage', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HomeLanguageSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyFinished', models.BooleanField()),
                ('surveyLanguage', models.CharField(blank=True, max_length=20)),
                ('homeLanguageOtherThanEnglishSpoken', models.NullBooleanField()),
                ('homeLanguageOtherThanEnglish', models.CharField(blank=True, max_length=100)),
                ('studentSpeaksLanguageOtherThanEnglish', models.NullBooleanField()),
                ('studentOtherLanguage', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MainSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyFinished', models.BooleanField()),
                ('studentID', models.CharField(blank=True, max_length=8)),
                ('lastName', models.CharField(blank=True, max_length=20)),
                ('firstName', models.CharField(blank=True, max_length=20)),
                ('middleName', models.CharField(blank=True, max_length=20)),
                ('generation', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, max_length=1)),
                ('entryGrade', models.IntegerField(blank=True)),
                ('birthCertOnFile', models.NullBooleanField()),
                ('birthVer', models.CharField(blank=True, max_length=100)),
                ('birthCountry', models.CharField(blank=True, max_length=50)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('birthCity', models.CharField(blank=True, max_length=100)),
                ('firstUSEnrollDate', models.DateField(blank=True, null=True)),
                ('numYearsUSSchooling', models.IntegerField(blank=True)),
                ('dateEnteredUS', models.DateField(blank=True, null=True)),
                ('refugeeStatus', models.NullBooleanField()),
                ('refugeeCountry', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MediaConsentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyCompleted', models.BooleanField()),
                ('consentToMedia', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PreviousSchoolSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyFinished', models.BooleanField()),
                ('schoolTransferringFrom', models.CharField(blank=True, max_length=100)),
                ('studentInGoodStanding', models.NullBooleanField()),
                ('lastPublicSchool', models.CharField(blank=True, max_length=100)),
                ('specialEdServices', models.BooleanField()),
                ('enrollerGuardianName', models.CharField(blank=True, max_length=200)),
                ('enrollerGuardianRelationship', models.CharField(blank=True, max_length=100)),
                ('enrollerGuardianSigned', models.NullBooleanField()),
                ('enrollmentDate', models.DateField(blank=True, null=True)),
                ('oldSchoolAddress', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='enroller.Address')),
            ],
        ),
        migrations.CreateModel(
            name='RaceAndEthnicitySurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyCompleted', models.BooleanField()),
                ('race', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activationCode', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=1000)),
                ('contactSurvey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroller.ContactSurvey')),
                ('emergencyAndHealthSurvey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroller.EmergencyAndHealthInfo')),
                ('homeLanguageSurvey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroller.HomeLanguageSurvey')),
                ('mainSurvey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroller.MainSurvey')),
                ('mediaConsentForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroller.MediaConsentForm')),
                ('previousSchoolSurvey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroller.PreviousSchoolSurvey')),
                ('raceAndEthnicitySurvey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroller.RaceAndEthnicitySurvey')),
            ],
        ),
        migrations.AddField(
            model_name='emergencyandhealthinfo',
            name='guardian1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardian1', to='enroller.Guardian'),
        ),
        migrations.AddField(
            model_name='emergencyandhealthinfo',
            name='guardian2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardian2', to='enroller.Guardian'),
        ),
    ]
