# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-02 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0002_auto_20170102_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsurvey',
            name='gender',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
