# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-10 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0003_auto_20170102_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyandhealthinfo',
            name='neighbor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighbor', to='enroller.Guardian'),
        ),
    ]
