# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-11 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0004_emergencyandhealthinfo_neighbor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsurvey',
            old_name='mailingAddress',
            new_name='mailingaddress',
        ),
        migrations.RenameField(
            model_name='contactsurvey',
            old_name='physicalAddress',
            new_name='physicaladdress',
        ),
        migrations.RenameField(
            model_name='previousschoolsurvey',
            old_name='oldSchoolAddress',
            new_name='oldschooladdress',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='contactSurvey',
            new_name='contactsurvey',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='emergencyAndHealthSurvey',
            new_name='emergencyandhealthinfo',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='homeLanguageSurvey',
            new_name='homelanguagesurvey',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mainSurvey',
            new_name='mainsurvey',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mediaConsentForm',
            new_name='mediaconsentform',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='previousSchoolSurvey',
            new_name='previousschoolsurvey',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='raceAndEthnicitySurvey',
            new_name='raceAndethnicitysurvey',
        ),
    ]
