# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0006_auto_20170114_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='workAddress',
        ),
    ]
