# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0007_remove_guardian_workaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='raceAndethnicitysurvey',
            new_name='raceandethnicitysurvey',
        ),
    ]
