# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-07 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0011_auto_20170207_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homelanguagesurvey',
            old_name='homelanguageotherthanenglish',
            new_name='homeLanguageOtherThanEnglish',
        ),
        migrations.RenameField(
            model_name='homelanguagesurvey',
            old_name='homelanguageotherthanenglishspoken',
            new_name='homeLanguageOtherThanEnglishSpoken',
        ),
        migrations.RenameField(
            model_name='homelanguagesurvey',
            old_name='studentotherlanguage',
            new_name='studentOtherLanguage',
        ),
        migrations.RenameField(
            model_name='homelanguagesurvey',
            old_name='studentspeakslanguageotherthanenglish',
            new_name='studentSpeaksLanguageOtherThanEnglish',
        ),
        migrations.RenameField(
            model_name='homelanguagesurvey',
            old_name='surveyfinished',
            new_name='surveyFinished',
        ),
        migrations.RenameField(
            model_name='homelanguagesurvey',
            old_name='surveylanguage',
            new_name='surveyLanguage',
        ),
    ]
