# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-08 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0012_auto_20170207_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previousschoolsurvey',
            old_name='studentinGoodStanding',
            new_name='studentInGoodStanding',
        ),
    ]
