# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0014_auto_20170208_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accountLocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='resetVal',
            field=models.CharField(default='asdfas', max_length=10),
            preserve_default=False,
        ),
    ]
