# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-22 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0015_auto_20170213_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='divisionNumber',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='schoolId',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
