# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-28 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0016_auto_20170222_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('pwd', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
