# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-03 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0017_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thefile', models.FileField(upload_to='csvs')),
            ],
        ),
    ]
