# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-13 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0019_auto_20170307_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleFile',
        ),
        migrations.RenameField(
            model_name='homelanguagesurvey',
            old_name='surveyFinished',
            new_name='surveyCompleted',
        ),
        migrations.RenameField(
            model_name='mainsurvey',
            old_name='surveyFinished',
            new_name='surveyCompleted',
        ),
        migrations.RenameField(
            model_name='previousschoolsurvey',
            old_name='surveyFinished',
            new_name='surveyCompleted',
        ),
    ]
