# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-13 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0020_auto_20170313_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsurvey',
            name='physicalAddressChanged',
            field=models.BooleanField(default=False),
        ),
    ]
