# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-13 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0021_contactsurvey_physicaladdresschanged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsurvey',
            old_name='physicalAddressChanged',
            new_name='mailingAddressChanged',
        ),
    ]
