# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-17 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0022_auto_20170313_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='divisionNumber',
        ),
    ]
