# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-17 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0023_remove_student_divisionnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
