# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-20 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroller', '0024_auto_20170317_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsurvey',
            name='birthDate',
            field=models.CharField(blank=True, default='3/20/2017', max_length=10),
            preserve_default=False,
        ),
    ]
